services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  db:
    image: mariadb
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: